server {
    listen 80;
    server_name localhost;
    index index.php index.html;
    root /var/www/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /storage {
        alias /var/www/storage/app/public;
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;

        fastcgi_param HTTP_HOST        $host;
        fastcgi_param REMOTE_ADDR      $remote_addr;

        # Tambahkan ini
        fastcgi_param HTTP_X_FORWARDED_FOR    $remote_addr;
        fastcgi_param HTTP_X_FORWARDED_HOST   $host:8000;
        fastcgi_param HTTP_X_FORWARDED_PORT   8000;
        fastcgi_param HTTP_X_FORWARDED_PROTO  http;

        fastcgi_buffering  off;
        fastcgi_keep_conn  on;
    }
}
